//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zashitniki.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilitaryActionMember
    {
        public int ID { get; set; }
        public int MilitaryActionID { get; set; }
        public int VeteranID { get; set; }
        public System.DateTime DataStart { get; set; }
        public System.DateTime DataEnd { get; set; }
    
        public virtual MilitaryAction MilitaryAction { get; set; }
        public virtual Veteran Veteran { get; set; }
    }
}
