//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zashitniki.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entitiess : DbContext
    {
        public Entitiess()
            : base("name=Entitiess")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Award> Award { get; set; }
        public virtual DbSet<AwardVeteran> AwardVeteran { get; set; }
        public virtual DbSet<Employe> Employe { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<EventVeteran> EventVeteran { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<MilitaryAction> MilitaryAction { get; set; }
        public virtual DbSet<MilitaryActionMember> MilitaryActionMember { get; set; }
        public virtual DbSet<MilitaryRank> MilitaryRank { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<PsychologicalSupport> PsychologicalSupport { get; set; }
        public virtual DbSet<SocialService> SocialService { get; set; }
        public virtual DbSet<SocialServiceVeteran> SocialServiceVeteran { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Veteran> Veteran { get; set; }
    }
}
